from copy import deepcopy

DEFAULT_ACTIVITY_RULE = {
    "activity_type": "activity",
    "category": "general",
    "tags": [],
    "estimated_cost_cents": None,
    "duration_minutes": None,
    "effort_level": 2,
    "accessibility_notes": None,
    "wheelchair_accessible": None,
    "family_friendly": None,
    "good_for_groups": None,
    "good_for_kids": None,
    "pet_friendly": None,
    "indoor_outdoor": "unknown",
    "noise_level": "unknown",
    "activity_level": "unknown",
    "reservations_required": None,
    "ticket_required": None,
    "source": "google",
    "source_url": None,
}


TYPE_PRIORITY = [
    "night_club",
    "amusement_park",
    "water_park",
    "museum",
    "art_gallery",
    "movie_theater",
    "zoo",
    "aquarium",
    "park",
    "tourist_attraction",
    "bar",
    "restaurant",
    "cafe",
]


GOOGLE_TYPE_RULES = {
    "museum": {
        "category": "museum",
        "tags": ["arts", "culture", "quiet"],
        "effort_level": 1,
        "family_friendly": True,
        "good_for_groups": True,
        "good_for_kids": False,
        "indoor_outdoor": "indoor",
        "noise_level": "quiet",
        "activity_level": "low",
        "ticket_required": True,
    },
    "art_gallery": {
        "category": "museum",
        "tags": ["art", "culture", "quiet"],
        "effort_level": 1,
        "family_friendly": False,
        "good_for_groups": True,
        "good_for_kids": False,
        "indoor_outdoor": "indoor",
        "noise_level": "quiet",
        "activity_level": "low",
        "ticket_required": False,
    },
    "movie_theater": {
        "category": "entertainment",
        "tags": ["movies", "indoor", "date-night"],
        "effort_level": 1,
        "family_friendly": True,
        "good_for_groups": True,
        "good_for_kids": True,
        "indoor_outdoor": "indoor",
        "noise_level": "average",
        "activity_level": "low",
        "ticket_required": True,
    },
    "night_club": {
        "category": "nightlife",
        "tags": ["music", "late-night", "social"],
        "effort_level": 2,
        "family_friendly": False,
        "good_for_groups": True,
        "good_for_kids": False,
        "indoor_outdoor": "indoor",
        "noise_level": "loud",
        "activity_level": "high",
        "reservations_required": False,
        "ticket_required": False,
    },
    "park": {
        "category": "outdoors",
        "tags": ["nature", "walking", "relaxing"],
        "effort_level": 1,
        "family_friendly": True,
        "good_for_groups": True,
        "good_for_kids": True,
        "pet_friendly": True,
        "indoor_outdoor": "outdoor",
        "noise_level": "quiet",
        "activity_level": "low",
        "ticket_required": False,
    },
    "zoo": {
        "category": "family",
        "tags": ["animals", "walking", "family"],
        "effort_level": 2,
        "family_friendly": True,
        "good_for_groups": True,
        "good_for_kids": True,
        "indoor_outdoor": "both",
        "noise_level": "average",
        "activity_level": "medium",
        "ticket_required": True,
    },
    "aquarium": {
        "category": "family",
        "tags": ["animals", "education", "indoor"],
        "effort_level": 1,
        "family_friendly": True,
        "good_for_groups": True,
        "good_for_kids": True,
        "indoor_outdoor": "indoor",
        "noise_level": "quiet",
        "activity_level": "low",
        "ticket_required": True,
    },
    "amusement_park": {
        "category": "thrill",
        "tags": ["rides", "fun", "social"],
        "effort_level": 3,
        "family_friendly": True,
        "good_for_groups": True,
        "good_for_kids": True,
        "indoor_outdoor": "both",
        "noise_level": "loud",
        "activity_level": "high",
        "ticket_required": True,
    },
    "water_park": {
        "category": "thrill",
        "tags": ["water", "rides", "summer"],
        "effort_level": 3,
        "family_friendly": True,
        "good_for_groups": True,
        "good_for_kids": True,
        "indoor_outdoor": "outdoor",
        "noise_level": "loud",
        "activity_level": "high",
        "ticket_required": True,
    },
    "tourist_attraction": {
        "category": "attraction",
        "tags": ["sightseeing", "popular"],
        "effort_level": 2,
        "family_friendly": True,
        "good_for_groups": True,
        "good_for_kids": True,
        "indoor_outdoor": "both",
        "noise_level": "average",
        "activity_level": "medium",
        "ticket_required": False,
    },
    "bar": {
        "category": "nightlife",
        "tags": ["drinks", "social", "casual"],
        "effort_level": 1,
        "family_friendly": False,
        "good_for_groups": True,
        "good_for_kids": False,
        "indoor_outdoor": "indoor",
        "noise_level": "average",
        "activity_level": "medium",
        "ticket_required": False,
    },
    "restaurant": {
        "category": "food",
        "tags": ["dining", "social"],
        "effort_level": 1,
        "family_friendly": True,
        "good_for_groups": True,
        "good_for_kids": True,
        "indoor_outdoor": "indoor",
        "noise_level": "average",
        "activity_level": "low",
        "reservations_required": False,
        "ticket_required": False,
    },
    "cafe": {
        "category": "food",
        "tags": ["coffee", "casual", "relaxing"],
        "effort_level": 1,
        "family_friendly": True,
        "good_for_groups": False,
        "good_for_kids": True,
        "indoor_outdoor": "indoor",
        "noise_level": "quiet",
        "activity_level": "low",
        "ticket_required": False,
    },
}


def get_default_activity_rule() -> dict:
    return deepcopy(DEFAULT_ACTIVITY_RULE)